const states = [
  ['AL', 'Alabama', 'آلاباما'],
  ['AK', 'Alaska', 'آلاسکا'],
  ['AZ', 'Arizona', 'آریزونا'],
  ['AR', 'Arkansas', 'آرکانزاس'],
  ['CA', 'California', 'کالیفرنیا'],
  ['CO', 'Colorado', 'کلرادو'],
  ['CT', 'Connecticut', 'کنتیکت'],
  ['DE', 'Delaware', 'دلاور'],
  ['FL', 'Florida', 'فلوریدا'],
  ['GA', 'Georgia', 'جورجیا'],
  ['HI', 'Hawaii', 'هاوایی'],
  ['ID', 'Idaho', 'آیداهو'],
  ['IL', 'Illinois', 'ایلینوی'],
  ['IN', 'Indiana', 'ایندیانا'],
  ['IA', 'Iowa', 'آیووا'],
  ['KS', 'Kansas', 'کانزاس'],
  ['KY', 'Kentucky', 'کنتاکی'],
  ['LA', 'Louisiana', 'لوئیزیانا'],
  ['ME', 'Maine', 'مین'],
  ['MD', 'Maryland', 'مریلند'],
  ['MA', 'Massachusetts', 'ماساچوست'],
  ['MI', 'Michigan', 'میشیگان'],
  ['MN', 'Minnesota', 'مینه‌سوتا'],
  ['MS', 'Mississippi', 'میسیسیپی'],
  ['MO', 'Missouri', 'میزوری'],
  ['MT', 'Montana', 'مونتانا'],
  ['NE', 'Nebraska', 'نبراسکا'],
  ['NV', 'Nevada', 'نوادا'],
  ['NH', 'New Hampshire', 'نیوهمپشایر'],
  ['NJ', 'New Jersey', 'نیوجرسی'],
  ['NM', 'New Mexico', 'نیومکزیکو'],
  ['NY', 'New York', 'نیویورک'],
  ['NC', 'North Carolina', 'کارولینای شمالی'],
  ['ND', 'North Dakota', 'داکوتای شمالی'],
  ['OH', 'Ohio', 'اوهایو'],
  ['OK', 'Oklahoma', 'اوکلاهما'],
  ['OR', 'Oregon', 'اورگن'],
  ['PA', 'Pennsylvania', 'پنسیلوانیا'],
  ['RI', 'Rhode Island', 'رود آیلند'],
  ['SC', 'South Carolina', 'کارولینای جنوبی'],
  ['SD', 'South Dakota', 'داکوتای جنوبی'],
  ['TN', 'Tennessee', 'تنسی'],
  ['TX', 'Texas', 'تگزاس'],
  ['UT', 'Utah', 'یوتا'],
  ['VT', 'Vermont', 'ورمانت'],
  ['VA', 'Virginia', 'ویرجینیا'],
  ['WA', 'Washington', 'واشنگتن'],
  ['WV', 'West Virginia', 'ویرجینیای غربی'],
  ['WI', 'Wisconsin', 'ویسکانسین'],
  ['WY', 'Wyoming', 'وایومینگ'],
] as const

export const stateOptions = states.map(([value, en, fa]) => ({
  label: { en, fa },
  value,
}))
